### ISSUE TITLE
violated single responsibility principle

### ISSUE THREAD

**Issue by nklhtv** [BattleFieldTwo/Teamwork#24]
The methods GetFieldSize, GetInputCoordinates, NotifyForInvalidMove, GameOver and GiveMinesCount have no place in View model. They have to be in the Game Engine.

**Comment by veselints** [comment]
The methods NotifyForInvalidMove, GameOver and GiveMinesCount only draw on the console. I think they have to be in the Renderer, but we have to change their names as they are not clear. We can change them to DisplayInvalidMoveMessage, DisplayGameOver and DisplayMinesCount.

You are right for the other two methods. They are placed there because I tried to make the engine abstract, so it doesn't draw on the console, but I didn't do it the right way. I think, this could be fixed by having these methods in the Engine and in them, we can call the methods from the Renderer that draw on the console.

**Comment by veselints** [comment]
Nikola, if you think you already resolved this issue implementing GameEngine and ConsoleRenderer, close it.
